import 'package:flutter/material.dart';

// COLORS FINAL
final List<Color> opacityBlack = <Color>[
  Colors.black.withOpacity(1.0),
  Colors.black.withOpacity(1.0),
  Colors.black.withOpacity(0.99),
  Colors.black.withOpacity(0.98),
  Colors.black.withOpacity(0.97),
  Colors.black.withOpacity(0.96),
  Colors.black.withOpacity(0.95),
  Colors.black.withOpacity(0.94),
  Colors.black.withOpacity(0.93),
  Colors.black.withOpacity(0.92),
  Colors.black.withOpacity(0.91),
  Colors.black.withOpacity(0.90),
  Colors.black.withOpacity(0.89),
  Colors.black.withOpacity(0.88),
  Colors.black.withOpacity(0.87),
  Colors.black.withOpacity(0.86),
  Colors.black.withOpacity(0.85),
  Colors.black.withOpacity(0.84),
  Colors.black.withOpacity(0.83),
  Colors.black.withOpacity(0.82),
  Colors.black.withOpacity(0.81),
  Colors.black.withOpacity(0.80),
  Colors.black.withOpacity(0.79),
  Colors.black.withOpacity(0.78),
  Colors.black.withOpacity(0.77),
  Colors.black.withOpacity(0.76),
  Colors.black.withOpacity(0.75),
  Colors.black.withOpacity(0.74),
  Colors.black.withOpacity(0.73),
  Colors.black.withOpacity(0.72),
  Colors.black.withOpacity(0.71),
  Colors.black.withOpacity(0.70),
  Colors.black.withOpacity(0.69),
  Colors.black.withOpacity(0.68),
  Colors.black.withOpacity(0.67),
  Colors.black.withOpacity(0.66),
  Colors.black.withOpacity(0.65),
  Colors.black.withOpacity(0.64),
  Colors.black.withOpacity(0.63),
  Colors.black.withOpacity(0.62),
  Colors.black.withOpacity(0.61),
  Colors.black.withOpacity(0.60),
  Colors.black.withOpacity(0.59),
  Colors.black.withOpacity(0.58),
  Colors.black.withOpacity(0.57),
  Colors.black.withOpacity(0.56),
  Colors.black.withOpacity(0.55),
  Colors.black.withOpacity(0.54),
  Colors.black.withOpacity(0.53),
  Colors.black.withOpacity(0.52),
  Colors.black.withOpacity(0.51),
  Colors.black.withOpacity(0.50),
  Colors.black.withOpacity(0.49),
  Colors.black.withOpacity(0.48),
  Colors.black.withOpacity(0.47),
  Colors.black.withOpacity(0.46),
  Colors.black.withOpacity(0.45),
  Colors.black.withOpacity(0.44),
  Colors.black.withOpacity(0.43),
  Colors.black.withOpacity(0.42),
  Colors.black.withOpacity(0.41),
  Colors.black.withOpacity(0.40),
  Colors.black.withOpacity(0.39),
  Colors.black.withOpacity(0.38),
  Colors.black.withOpacity(0.37),
  Colors.black.withOpacity(0.36),
  Colors.black.withOpacity(0.35),
  Colors.black.withOpacity(0.34),
  Colors.black.withOpacity(0.33),
  Colors.black.withOpacity(0.32),
  Colors.black.withOpacity(0.31),
  Colors.black.withOpacity(0.30),
  Colors.black.withOpacity(0.29),
  Colors.black.withOpacity(0.28),
  Colors.black.withOpacity(0.27),
  Colors.black.withOpacity(0.26),
  Colors.black.withOpacity(0.25),
  Colors.black.withOpacity(0.24),
  Colors.black.withOpacity(0.23),
  Colors.black.withOpacity(0.22),
  Colors.black.withOpacity(0.21),
  Colors.black.withOpacity(0.20),
  Colors.black.withOpacity(0.19),
  Colors.black.withOpacity(0.18),
  Colors.black.withOpacity(0.17),
  Colors.black.withOpacity(0.16),
  Colors.black.withOpacity(0.15),
  Colors.black.withOpacity(0.14),
  Colors.black.withOpacity(0.13),
  Colors.black.withOpacity(0.12),
  Colors.black.withOpacity(0.10),
  Colors.black.withOpacity(0.09),
  Colors.black.withOpacity(0.08),
  Colors.black.withOpacity(0.07),
  Colors.black.withOpacity(0.06),
  Colors.black.withOpacity(0.05),
  Colors.black.withOpacity(0.04),
  Colors.black.withOpacity(0.03),
  Colors.black.withOpacity(0.02),
  Colors.black.withOpacity(0.02),
  Colors.black.withOpacity(0.01),
  Colors.black.withOpacity(0.01),
  Colors.black.withOpacity(0.00),
];
final Color white = Colors.white;
final Color black = Colors.black;
final Color yellow = Colors.yellow;
final Color transparent = Color.fromRGBO(255, 255, 255, 0.0);
final Color primary = Color.fromRGBO(255, 128, 0, 1.0);
final Color facebook = Color(0xff4267B2);
final Color colorGmail = Color(0xffDB4437);
final Color greyTitles = Color.fromRGBO(047, 053, 059, 1.0);
final Color greySubTitles = Color.fromRGBO(071, 074, 081, 1.0);
final Color greyText = Color.fromRGBO(078, 087, 084, 1.0);
final Color greyFilling = Color.fromRGBO(142, 142, 147, 1.2);
final Color greyHintText = Color.fromRGBO(141, 148, 141, 1.0);
final Color greyOpcity = Color.fromRGBO(0, 0, 0, 1.3);
